// #region LIB
/// <reference path="assets/js/lib/polyfills.js"/>
/// <reference path="assets/js/lib/native-object-extensions.js"/>
/// <reference path="assets/js/lib/guard.js"/>
/// <reference path="assets/js/lib/register.js"/>
/// <reference path="assets/js/lib/vendor-attributes.js"/>
/// <reference path="assets/js/lib/user-agent.js"/>
/// <reference path="assets/js/lib/timer.js"/>
/// <reference path="assets/js/lib/image.js"/>
/// <reference path="assets/js/lib/font.js"/>
/// <reference path="assets/js/lib/animation.js"/>
/// <reference path="assets/js/lib/sound.js"/>
/// <reference path="assets/js/lib/media-factory.js"/>
// #endregion LIB

// #region CORE
/// <reference path="assets/js/core/debug.js"/>
/// <reference path="assets/js/core/entity.js"/>
/// <reference path="assets/js/core/game.js"/>
/// <reference path="assets/js/core/input.js"/>
/// <reference path="assets/js/core/loader.js"/>
/// <reference path="assets/js/core/loop.js"/>
/// <reference path="assets/js/core/map.js"/>
/// <reference path="assets/js/core/runner.js"/>
/// <reference path="assets/js/core/system.js"/>
// #endregion CORE

// #region CUSTOM
/// <reference path="assets/js/pong-entities.js"/>
/// <reference path="assets/js/level.js"/>
/// <reference path="assets/js/my-game.js"/>
// #endregion CUSTOM
