// #region LIB
/// <reference path="assets/js/lib/polyfills.js"/>
/// <reference path="assets/js/lib/native-object-extensions.js"/>
/// <reference path="assets/js/lib/guard.js"/>
/// <reference path="assets/js/lib/register.js"/>
/// <reference path="assets/js/lib/vendor-attributes.js"/>
/// <reference path="assets/js/lib/user-agent.js"/>
/// <reference path="assets/js/lib/timer.js"/>
/// <reference path="assets/js/lib/input.js"/>
/// <reference path="assets/js/lib/image.js"/>
/// <reference path="assets/js/lib/font.js"/>
/// <reference path="assets/js/lib/animation.js"/>
/// <reference path="assets/js/lib/sound.js"/>
/// <reference path="assets/js/lib/map.js"/>
/// <reference path="assets/js/lib/media-factory.js"/>
// #endregion LIB

// #region CORE
/// <reference path="assets/js/core/game-loop.js"/>
/// <reference path="assets/js/core/entity.js"/>
/// <reference path="assets/js/core/system.js"/>
/// <reference path="assets/js/core/game.js"/>
/// <reference path="assets/js/core/runner.js"/>
/// <reference path="assets/js/core/game-loader.js"/>
// #endregion CORE

// #region DEBUG
/// <reference path="assets/js/debug/performance.js"/>
/// <reference path="assets/js/debug/debug-menu.js"/>
/// <reference path="assets/js/debug/panels/entities.js"/>
/// <reference path="assets/js/debug/panels/graph.js"/>
/// <reference path="assets/js/debug/panels/maps.js"/>
// #endregion DEBUG

// #region CUSTOM
/// <reference path="assets/js/pong-entities.js"/>
/// <reference path="assets/js/level.js"/>
/// <reference path="assets/js/my-game.js"/>
// #endregion CUSTOM
