// #region LIB
/// <reference path="src/lib/polyfills.js"/>
/// <reference path="src/lib/native-object-extensions.js"/>
/// <reference path="src/lib/guard.js"/>
/// <reference path="src/lib/register.js"/>
/// <reference path="src/lib/vendor-attributes.js"/>
/// <reference path="src/lib/user-agent.js"/>
/// <reference path="src/lib/timer.js"/>
/// <reference path="src/lib/image.js"/>
/// <reference path="src/lib/font.js"/>
/// <reference path="src/lib/animation.js"/>
/// <reference path="src/lib/sound.js"/>
/// <reference path="src/lib/media-factory.js"/>
// #endregion LIB

// #region CORE
/// <reference path="src/debug/performance-stats.js"/>
/// <reference path="src/debug/debug.js"/>
/// <reference path="src/core/entity.js"/>
/// <reference path="src/core/game.js"/>
/// <reference path="src/core/input.js"/>
/// <reference path="src/core/loader.js"/>
/// <reference path="src/core/loop.js"/>
/// <reference path="src/core/map.js"/>
/// <reference path="src/core/runner.js"/>
/// <reference path="src/core/system.js"/>
// #endregion CORE

// #region CUSTOM
/// <reference path="src/pong-entities.js"/>
/// <reference path="src/level.js"/>
/// <reference path="src/my-game.js"/>
// #endregion CUSTOM
